language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "exploding-kittens-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: explodekittens
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: 1BaCq+bFKsKYpS0skbbQbembs0dT/CFdUuDwEcA1aBxpCY53OmPiVewncUIlPquF71CPLeqKRvx9LbSFcMlHmp/JnHIrmBEoQcGeu9XUDr+Jtqe91a4NyvHPTi9gM/nqU3gISh1PFxL0N4642Wz6sMTceTnhCuI1orpbHYcgH56uH+6OmqH5RCZKoXyoSRPZwLIkhfX1e8IHraB1AshXad5dqu3pnyWW/iVgJRs9Nzc/PBMcgF3RnfM+2uabxULp1XhloGKhf/s7KnXZyCB7uA98SfQfawF/1cyFV58Fs5Ch4HZc6rAqKgXSu6lzFtl14ZOb6uXzN/CngpOdZs6ZNvWCZGus4aMdrS3KLI393iUR3bX5CVJko0C0TAcNChkbymaNK6kXz7RjcBpN6KlZwpMZBaxboinI8yOeL2p9WCdKbj2sudZ2hmUIPjkgbIQbVs5Mb/hrMCfLpobvx+R5iO0MxEtagVYmmDaBuJCVL+NOGjnjJFGSriSMMOrM3y77lqOKq/wEwhY25Ca6VX53trfFBrAkOr+kptFfyC968ohO9YlS1lxD5lDvdx0G5yn1pjcN7e9M1j+f2ZO6byhtNkPJGyhU3WFo4nizN4RzpwQ+3H0Sh6c3f8TostOQwS2pNVq0oMvQGjJWsusorDLT5EIZcxPc2slSUWE5m8B7DvU=
